language: swift
xcode_workspace: Example/InAppMessaging.xcworkspace
xcode_scheme: InAppMessaging-Example
osx_image: xcode11.3

script:
  - travis_wait bundle exec fastlane ci
  - bundle exec danger

cache:
  - bundler

before_install:
  # update necessary pods only instead of running `pod repo update`
  # https://github.com/travis-ci/travis-ci/issues/6473 
  - pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed it for" $2 } }'

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^RInAppMessaging$'
  - pod lib lint
  # generate docs
  - bundle exec jazzy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PUBLISHER_GITHUB_API_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
