language: swift
xcode_workspace: Example/InAppMessaging.xcworkspace
xcode_scheme: InAppMessaging-Example
osx_image: xcode11.5

script:
  - travis_wait bundle exec fastlane ci
  - bundle exec danger

cache:
  - bundler

before_install:
  # update necessary pods only instead of running `pod repo update`
  # https://github.com/travis-ci/travis-ci/issues/6473 
  - pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed it for" $2 } }'

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^RInAppMessaging$' -X gcov
  # generate docs (no PRs)
  - test $TRAVIS_PULL_REQUEST = "false" && bundle exec jazzy

deploy:
  # When tagged with version (X.X.X)
  # Deploy Pod spec
  - provider: script
    edge: true
    script:
      bundle exec pod spec lint --allow-warnings;
      bundle exec pod trunk push --allow-warnings --verbose
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
  # Deploy Docs to Github Pages
  - provider: pages
    edge: true
    github_token: $PUBLISHER_GITHUB_API_TOKEN
    keep_history: true
    local_dir: docs
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
